from os import getenv
from dotenv import load_dotenv
load_dotenv()

class process:
    class env:
        aws_access_key_id = getenv('aws_access_key_id')
        aws_secret_access_key = getenv('aws_secret_access_key')
        aws_user_pool_id = getenv('aws_user_pool_id')
        aws_app_client_id = getenv('aws_app_client_id')
        aws_app_client_secret = getenv('aws_app_client_secret')
        aws_region_name = getenv('aws_region_name')
        fauna_secret = getenv('fauna_secret')
        firebase_api_key = getenv('firebase_api_key')
        firebase_auth_domain = getenv('firebase_auth_domain')
        firebase_project_id = getenv('firebase_project_id')
        firebase_storage_bucket = getenv('firebase_storage_bucket')
        firebase_messaging_sender_id = getenv('firebase_messaging_sender_id')
        firebase_app_id = getenv('firebase_app_id')
        firebase_measurement_id = getenv('firebase_measurement_id')
        auth0_domain = getenv('auth0_domain')
        auth0_client_id = getenv('auth0_client_id')
        auth0_client_secret =  getenv('auth0_client_secret')
        auth0_audience = getenv('auth0_audience')
        auth0_grant_type= getenv('auth0_grant_type')
        auth0_custom_api_id = getenv('auth0_custom_api_id')
        auth0_custom_api_identifier = getenv('auth0_custom_api_identifier')
        twilio_account_sid = getenv('twilio_account_sid')
        twilio_auth_token = getenv('twilio_auth_token')
        twilio_phone_number = getenv('twilio_phone_number')
        cognito_url= getenv('cognito_url')
        api_key= getenv('api_key')
        pexels_base_url= getenv('pexels_base_url')
        videos_base_url= getenv('videos_base_url')